name: crabify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audio_session: ^0.2.3
  provider: ^6.1.5+1
  dio: ^5.9.2
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  audio_service: ^0.18.18
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  audio_metadata_reader: ^1.4.2
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.9.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: assets/icon/icon.png